services:
  backend:
    container_name: jenkins-backend
    image: sauravdwivedi/jenkins-docker-fullstack-backend:latest
    build: ./backend
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=app
      - FLASK_DEBUG=1
      - PYTHONPATH=/src:/src/backend:/src/backend/controllers
    networks:
      - jenkins-docker-fullstack
  frontend:
    container_name: jenkins-frontend
    image: sauravdwivedi/jenkins-docker-fullstack-frontend:latest
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - jenkins-docker-fullstack

networks:
  jenkins-docker-fullstack:
    driver: bridge